version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homelibrary
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nest-app:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - app-logs:/app/logs 
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app-network

  nest-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - app-logs:/app/logs 
    command: npm run start:dev
    ports:
      - "4001:4000"
    depends_on:
      - postgres
    networks:
      - app-network
    profiles:
      - dev

volumes:
  pgdata: 
  app-logs:

networks:
  app-network:
    driver: bridge
